// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package paxoskv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaxosKVClient is the client API for PaxosKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosKVClient interface {
	Prepare(ctx context.Context, in *Proposer, opts ...grpc.CallOption) (*Acceptor, error)
	Accept(ctx context.Context, in *Proposer, opts ...grpc.CallOption) (*Acceptor, error)
}

type paxosKVClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosKVClient(cc grpc.ClientConnInterface) PaxosKVClient {
	return &paxosKVClient{cc}
}

func (c *paxosKVClient) Prepare(ctx context.Context, in *Proposer, opts ...grpc.CallOption) (*Acceptor, error) {
	out := new(Acceptor)
	err := c.cc.Invoke(ctx, "/PaxosKV/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosKVClient) Accept(ctx context.Context, in *Proposer, opts ...grpc.CallOption) (*Acceptor, error) {
	out := new(Acceptor)
	err := c.cc.Invoke(ctx, "/PaxosKV/Accept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosKVServer is the server API for PaxosKV service.
// All implementations must embed UnimplementedPaxosKVServer
// for forward compatibility
type PaxosKVServer interface {
	Prepare(context.Context, *Proposer) (*Acceptor, error)
	Accept(context.Context, *Proposer) (*Acceptor, error)
	mustEmbedUnimplementedPaxosKVServer()
}

// UnimplementedPaxosKVServer must be embedded to have forward compatible implementations.
type UnimplementedPaxosKVServer struct {
}

func (UnimplementedPaxosKVServer) Prepare(context.Context, *Proposer) (*Acceptor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPaxosKVServer) Accept(context.Context, *Proposer) (*Acceptor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedPaxosKVServer) mustEmbedUnimplementedPaxosKVServer() {}

// UnsafePaxosKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosKVServer will
// result in compilation errors.
type UnsafePaxosKVServer interface {
	mustEmbedUnimplementedPaxosKVServer()
}

func RegisterPaxosKVServer(s grpc.ServiceRegistrar, srv PaxosKVServer) {
	s.RegisterService(&PaxosKV_ServiceDesc, srv)
}

func _PaxosKV_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proposer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosKVServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PaxosKV/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosKVServer).Prepare(ctx, req.(*Proposer))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosKV_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proposer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosKVServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PaxosKV/Accept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosKVServer).Accept(ctx, req.(*Proposer))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosKV_ServiceDesc is the grpc.ServiceDesc for PaxosKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PaxosKV",
	HandlerType: (*PaxosKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _PaxosKV_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _PaxosKV_Accept_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxoskv.proto",
}
